services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    environment:
      - TZ=Asia/Ho_Chi_Minh

volumes:
  mongodb:
